const ShopActionTypes = {
  FETCH_COLLECTION_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTION_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};

export default ShopActionTypes;
